spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/weichao1996/springcloudConfig/
          searchPaths: src                        ##指定git的路径
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      